### ISSUE TITLE
GPU version crashes with cuMemFree failed.

### ISSUE THREAD

**Issue by dan-silver** [QuarkStar/SPH#9]
To get the error, run the sim with ```python sph.py -g 500 --interval=100 --mode=parallel```

Currently trying to reproduce this in a testing environment, outside of the simulation.

Full error:
```
Traceback (most recent call last):
  File "sph.py", line 22, in <module>
    main()
  File "sph.py", line 13, in main
    cli.startSimulation(ppos)
  File "/home/ubuntu/sph/cli.py", line 179, in startSimulation
    self.args.interval, self.args.savefile, self.args.timestep, self.args.mode)
  File "/home/ubuntu/sph/framework.py", line 124, in sim
    particles = gpu_particles.getResultsFromDevice()
  File "/home/ubuntu/sph/gpu_interface.py", line 67, in getResultsFromDevice
    return [Particle.unflatten(raw_data) for raw_data in self.particles_array.getDataFromDevice()[0]]
  File "/home/ubuntu/sph/gpu_interface.py", line 27, in getDataFromDevice
    return cuda.from_device(self.data, self.shape, self.dtype)
  File "/usr/local/lib/python2.7/dist-packages/pycuda-2014.1-py2.7-linux-x86_64.egg/pycuda/driver.py", line 782, in from_device
    memcpy_dtoh(result, devptr)
pycuda._driver.LogicError: cuMemcpyDtoH failed: invalid/unknown error code
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: invalid/unknown error code
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: invalid/unknown error code
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: invalid/unknown error code
```

**Comment by dan-silver** [comment]
Fixed in bd0260bc5be5119d3c00c4970aab05e85cb1b6b5
